name: compile example-all
on: 
  workflow_dispatch:
  push:
    paths:
      - 'example-all/**'
  
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "example-all/*.tex"
          glob_root_file: true
          work_in_root_file_dir: true
      - run: |
          git config user.name "LaTeX Compile Bot"
          git config user.email "actions@github.com"
          mkdir -p pdf
          mkdir -p pdf/example-all
          rsync -c example-all/*.pdf pdf/example-all
          git add pdf
          if [[ $(git diff HEAD --stat) == '' ]]; then (echo 'Working tree is clean') 
          else (git commit -m "compile example-all pdf"  && git push) fi

